services:
    _defaults:
        autowire: true
        autoconfigure: true

    Vrl\InlineEditableBundle\Twig\InlineEditableExtension:
        tags:
            - { name: twig.extension }

    Vrl\InlineEditableBundle\Twig\InlineEditableRuntime:
        arguments:
            $twig: '@twig'
            $themes: '%inline_editable.themes%'
            $editMode: '%inline_editable.edit_mode%'

