services:
    _defaults:
        autowire: true
        autoconfigure: true

    Vrl\InlineEditableBundle\Twig\InlineEditableExtension:
        arguments:
            $twig: '@twig'
            $themes: '%inline_editable.themes%'
        tags:
            - { name: twig.extension }

